### ISSUE TITLE
GUI inspector sync throws error

### ISSUE THREAD

**Issue by ghost** [gnuradio/gr-inspector#29]
```
self.inspector_qtgui_sink_vf_0 = Template error: #set $win = 'self._%s_win'%$id
    inspector.qtgui_inspector_sink_vf($samp_rate, $fft_len, $cfreq, $rf_unit, $msgports, $manual)
    self._$(id)_win = sip.wrapinstance(self.$(id).pyqwidget(), Qt.QWidget)
    $(gui_hint()($win))
```
Any idea on how to fix this I see it being injected through the make in the xml block. Not sure what your trying to do with it. It appears to be commented out.

        'str' object is not callable

**Comment by sbmueller** [comment]
This is analog to all other gnuradio qtgui blocks, see https://github.com/gnuradio/gnuradio/blob/v3.7.9.3/gr-qtgui/grc/qtgui_label.xml#L15 . It ensures that all QT widgets can be displayed in one window. The hash is not a comment.
Probably some API has been changed in Qt5 which needs this template string to be adapted as well. Maybe you can have a look at the current qtgui files, like https://github.com/gnuradio/gnuradio/blob/master/gr-qtgui/grc/qtgui_label.block.yml to adapt the string accordingly.

Closing this issue since it seems to be a Qt5 issue, which is not supported.
